@ Only contains the text for the Mauville Man named Giddy. The rest is in scripts/mauville_man.inc
GiddyText_SoPretty::
	.string "{COLOR BLUE} so pretty!$"

GiddyText_SoDarling::
	.string "{COLOR BLUE} so darling!$"

GiddyText_SoRelaxed::
	.string "{COLOR BLUE} so relaxed!$"

GiddyText_SoSunny::
	.string "{COLOR BLUE} so sunny!$"

GiddyText_SoDesirable::
	.string "{COLOR BLUE} so desirable!$"

GiddyText_SoExciting::
	.string "{COLOR BLUE} so exciting!$"

GiddyText_SoAmusing::
	.string "{COLOR BLUE} so amusing!$"

GiddyText_SoMagical::
	.string "{COLOR BLUE} so magical!$"

GiddyText_Is::
	.string "{COLOR BLUE} is$"

GiddyText_DontYouAgree::
	.string "{COLOR BLUE}\n"
	.string "Don't you agree?$"

GiddyText_ISoWantToGoOnAVacation::
	.string "{COLOR BLUE}I so want to go on a vacation.\n"
	.string "Would you happen to know a nice place?$"

GiddyText_IBoughtCrayonsWith120Colors::
	.string "{COLOR BLUE}I bought crayons with 120 colors!\n"
	.string "Don't you think that's nice?$"

GiddyText_WouldntItBeNiceIfWeCouldFloat::
	.string "{COLOR BLUE}Wouldn't it be nice if we could float\n"
	.string "away on a cloud of bubbles?$"

GiddyText_WhenYouWriteOnASandyBeach::
	.string "{COLOR BLUE}When you write on a sandy beach,\n"
	.string "they wash away. It makes me sad.$"

GiddyText_WhatsTheBottomOfTheSeaLike::
	.string "{COLOR BLUE}What's the bottom of the sea like?\n"
	.string "Just once I would so love to go!$"

GiddyText_WhenYouSeeTheSettingSunDoesIt::
	.string "{COLOR BLUE}When you see the setting sun, does it\n"
	.string "make you want to go home?$"

GiddyText_LyingBackInTheGreenGrass::
	.string "{COLOR BLUE}Lying back in the green grass…\n"
	.string "Oh, it's so, so nice!$"

GiddyText_SecretBasesAreSoWonderful::
	.string "{COLOR BLUE}SECRET BASES are so wonderful!\n"
	.string "Can't you feel the excitement?$"
