Common_EventScript_FindItem::
	callnative GetObjectEventTrainerRangeFromTemplate
	finditem VAR_RESULT
	end
//This will be the script all item balls will use when using this feature. Essentially, it gets the value of VAR_RESULT and uses it for the parameter of finditem.
//Credits to Deokishishu
// As long as the script set for the item ball object is set to Common_EventScript_FindItem, you can use the Sight Radius/Berry Tree ID field in porymap to get the item ID you're wanting.
//If the script is NOT set however, it will not work.
